### PR TITLE
Simple android-orientation design for beginners.

### PR DESCRIPTION
**Pull request by tech-aziz**
Hi,
I have redesign the whole things. Added 4 component like username, password, sign up, and sign in options. This look so much professional right now.
Hopefully you will merge this codes with your main branch.
Thanks.

### CODE REVIEW

**Review by arifbd — COMMENTED** [review]
I've updated your code.

**Review by arifbd — COMMENTED** [review]
I've changed your few lines of code. please create a new pull request with the updated code.

**Comment by tech-aziz** [comment]
ok . pul request is already sent.

**Comment by arifbd** [comment]
> ok . pul request is already sent.

now send pull request again.

**Pull request closed without merging**
